//Practical Exercise 1: REST API

public class WeatherLocationAccount {
    // public static HttpResponse getCallout() {

    //     Http http = new Http();
    //     HttpRequest request = new HttpRequest();
    //     request.setEndpoint('https://openweathermap.org/current');
    //     request.setMethod('GET');
    //     HttpResponse response = http.send(request);

    //     if(response.getStatusCode() == 200) {
    //         System.debug(response.getBody());


    //     }
    // }
}